name: Release Module

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow on version tags like v1.0.0, v1.1.0, etc.

permissions:
  contents: write  # Required to upload assets to the release
  id-token: write  # Needed to interact with GitHub's authentication service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist directory and zip the project
        run: |
          mkdir -p dist
          zip -r dist/your-module-${{ github.ref }}.zip . -x ".git/*"  # Exclude .git files

      - name: Create versioned manifest
        run: |
          mkdir -p dist/v${{ github.ref }}
          echo '{
            "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/module.json",
            "download": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/your-module-${{ github.ref }}.zip"
          }' > dist/v${{ github.ref }}/module.json

      - name: Create latest manifest
        run: |
          echo '{
            "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/module.json",
            "download": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/your-module-${{ github.ref }}.zip"
          }' > dist/latest.json

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/your-module-${{ github.ref }}.zip
            dist/v${{ github.ref }}/module.json
            dist/latest.json
