name: Release Module

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # To upload assets to the release
  id-token: write  # To allow interaction with GitHub's authentication service
  actions: read  # For action to interact with the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release zip
        run: |
          zip -r your-module-${{ github.ref }}.zip *  # Adjust to match your project structure

      - name: Create versioned manifest
        run: |
          echo '{
            "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/module.json",
            "download": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/your-module-${{ github.ref }}.zip"
          }' > "v${{ github.ref }}/module.json"

      - name: Create latest manifest
        run: |
          echo '{
            "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/module.json",
            "download": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/your-module-${{ github.ref }}.zip"
          }' > latest.json

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            your-module-${{ github.ref }}.zip
            v${{ github.ref }}/module.json
            latest.json
