name: Release Module

on:
  push:
    tags:
      - 'v*'  # Trigger this workflow on version tags like v1.0.0, v1.1.0, etc.

permissions:
  contents: write  # Required to upload assets to the release
  id-token: write  # Needed to interact with GitHub's authentication service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dist directory and zip the project
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # Remove refs/tags/ to get the clean version
          mkdir -p dist
          zip -r dist/foundry-clippy-${VERSION}.zip . -x ".github/*"  # Exclude .git files

      - name: Create versioned manifest
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # Remove refs/tags/ to get the clean version
          mkdir -p dist/v${VERSION}
          echo "{\"manifest\": \"https://github.com/${{ github.repository }}/releases/download/v${VERSION}/module.json\", \"download\": \"https://github.com/${{ github.repository }}/releases/download/v${VERSION}/your-module-${VERSION}.zip\"}" > dist/v${VERSION}/module.json

      - name: Create latest manifest
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # Remove refs/tags/ to get the clean version
          echo "{\"manifest\": \"https://github.com/${{ github.repository }}/releases/download/v${VERSION}/module.json\", \"download\": \"https://github.com/${{ github.repository }}/releases/download/v${VERSION}/your-module-${VERSION}.zip\"}" > dist/latest.json

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/foundry-clippy-${VERSION}.zip
            dist/v${VERSION}/module.json
            dist/latest.json
